name: Convert_Resource_Stone_to_Wood_10x
clonePrefabName: Wood
craftingStation: $piece_stonecutter
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Stone:10:1:True
