
ores_miners:
  individualConfiguredObjects:
    BOM_FlintMine01:
      name: Flint Miner 1
      isPermanent: true
      isActive: true
    BOM_FlintMine02:
      name: Flint Miner 2
      isPermanent: true
      isActive: true
    BOM_CopperMine01:
      name: Copper Miner 1
      isPermanent: true
      isActive: true
    BOM_CopperMine02:
      name: Copper Miner 2
      isPermanent: true
      isActive: true
    BOM_TinMine01:
      name: Tin Miner 1
      isPermanent: true
      isActive: true
    BOM_TinMine02:
      name: Tin Miner 2
      isPermanent: true
      isActive: true
    BOM_CoalMine01:
      name: Coal Miner 1
      isPermanent: true
      isActive: true
    BOM_CoalMine02:
      name: Coal Miner 2
      isPermanent: true
      isActive: true
    BOM_IronMine01:
      name: Iron Miner 1
      isPermanent: true
      isActive: true
    BOM_IronMine02:
      name: Iron Miner 2
      isPermanent: true
      isActive: true
    BOM_SilverMine01:
      name: Silver Miner 1
      isPermanent: true
      isActive: true
    BOM_SilverMine02:
      name: Silver Miner 2
      isPermanent: true
      isActive: true
  iconName: mine
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 120
    green: 120
    blue: 120
    alpha: 255

ores_copper:
  categoryConfiguredObjects:
    - rock4_copper
  name: Copper Deposit
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 200
    green: 150
    blue: 115
    alpha: 255

ores_tin:
  categoryConfiguredObjects:
    - MineRock_Tin
  name: Tin
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 200
    green: 200
    blue: 200
    alpha: 255

ores_silver:
  categoryConfiguredObjects:
    - silvervein
  name: Silver Vein
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 150
    green: 150
    blue: 150
    alpha: 255

ores_obsidian:
  categoryConfiguredObjects:
    - MineRock_Obsidian
  name: Obsidian
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 135
    green: 70
    blue: 200
    alpha: 255

spawners:
  individualConfiguredObjects:
    CharredStone_Spawner:
      name: Skeletons
      isPermanent: true
      isActive: true
    BonePileSpawner:
      name: Skeletons
      isPermanent: true
      isActive: true
    GraveStone_Broken_CharredTwitcherNest:
      name: Twitcher
      isPermanent: true
      isActive: true
    GraveStone_CharredTwitcherNest:
      name: Twitcher
      isPermanent: true
      isActive: true
    Spawner_CharredCross:
      name: Skeletons
      isPermanent: true
      isActive: true
    Spawner_CharredStone:
      name: Skeletons
      isPermanent: true
      isActive: true
    Spawner_DraugrPile:
      name: Draugr
      isPermanent: true
      isActive: true
  iconName: spawner
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 255
    green: 100
    blue: 0
    alpha: 255

# MineRock_gold, MineRock_coal, MineRock_silver_small, MineRock_blackmetal





#region Meadows
# +---------+
# | Meadows |
# +---------+

dungeons_has_treasure_wood_house:
  categoryConfiguredObjects:
  - WoodHouse1
  - WoodHouse2
  - WoodHouse3
  - WoodHouse4
  - WoodHouse5
  - WoodHouse6
  - WoodHouse7
  - WoodHouse8
  - WoodHouse9
  - WoodHouse10
  - WoodHouse11
  - WoodHouse12
  - WoodHouse13
  name: Wood House
  iconName: village
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 75
    green: 35
    blue: 0
    alpha: 255



#region Black Forest
# +--------------+
# | Black Forest |
# +--------------+

dungeons_has_treasure_greydwarf_ruins:
  categoryConfiguredObjects:
    - Ruin1
    - Ruin2
    - Ruin3
  name: Ruins
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 150
    green: 150
    blue: 150
    alpha: 255

dungeons_has_treasure_stone_house:
  categoryConfiguredObjects:
  - StoneHouse3
  - StoneHouse4
  name: Stone House
  iconName: temple
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 140
    green: 140
    blue: 140
    alpha: 255

dungeons_has_treasure_stone_tower:
  categoryConfiguredObjects:
  - StoneTower1
  - StoneTower3
  - StoneTowerRuins03
  - StoneTowerRuins04
  - StoneTowerRuins05
  - StoneTowerRuins07
  - StoneTowerRuins08
  - StoneTowerRuins09
  - StoneTowerRuins10
  name: Stone Tower
  iconName: monument
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 140
    green: 140
    blue: 140
    alpha: 255

dungeon_crypt:
  categoryConfiguredObjects:
  - Crypt2
  - Crypt3
  - Crypt4
  name: Crypt
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 255
    green: 255
    blue: 255
    alpha: 255

dungeon_troll_cave:
  categoryConfiguredObjects:
  - TrollCave02
  name: Troll Cave
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 0
    green: 0
    blue: 255
    alpha: 255

spawner_greydwarf_nest:
  categoryConfiguredObjects:
  - Spawner_GreydwarfNest
  - Greydwarf_camp1
  name: Spawner Greydwarf
  iconName: spawner
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 0
    green: 255
    blue: 0
    alpha: 255



#region Swamp
# +-------+
# | Swamp |
# +-------+

dungeons_has_treasure_swamp_towers:
  categoryConfiguredObjects:
    - SwampRuin1
    - SwampRuin2
  name: Swamp Tower
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 150
    green: 150
    blue: 150
    alpha: 255

dungeons_has_treasure_swamp_huts:
  categoryConfiguredObjects:
    - SwampHut1
    - SwampHut2
    - SwampHut3
    - SwampHut4
    - SwampHut5
  name: Swamp Hut
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 105
    green: 40
    blue: 0
    alpha: 255

dungeon_sunken_crypt:
  categoryConfiguredObjects:
  - SunkenCrypt4
  name: Sunken Crypt
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 80
    green: 80
    blue: 80
    alpha: 255

spawner_surtlings:
  categoryConfiguredObjects:
  - FireHole
  name: Spawner Surtlings
  iconName: spawner
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 255
    green: 0
    blue: 0
    alpha: 255

ores_iron_deposit:
  categoryConfiguredObjects:
    - MineRock_iron
  name: Iron Deposit
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 155
    green: 155
    blue: 155
    alpha: 255

ores_coal_deposit:
  categoryConfiguredObjects:
    - MineRock_coal
  name: Coal Deposit
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 50
    green: 50
    blue: 50
    alpha: 255



#region Mountains
# +-----------+
# | Mountains |
# +-----------+

dungeons_has_treasure_abandoned_log_cabin:
  categoryConfiguredObjects:
  - AbandonedLogCabin02
  - AbandonedLogCabin03
  - AbandonedLogCabin04
  name: Abandoned Cabin
  iconName: village
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 150
    green: 75
    blue: 0
    alpha: 255

dungeon_mountain_cave:
  categoryConfiguredObjects:
  - MountainCave02
  name: Mountain Cave
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 0
    green: 255
    blue: 255
    alpha: 255

spawner_drake_nest:
  categoryConfiguredObjects:
  - DrakeNest01
  name: Drake Nest
  iconName: hand
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 200
    green: 0
    blue: 0
    alpha: 255



#region Plains
# +--------+
# | Plains |
# +--------+

spawner_tarpits:
  categoryConfiguredObjects:
  - TarPit1
  - TarPit2
  - TarPit3
  name: Spawner TarPit
  iconName: spawner
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 35
    green: 35
    blue: 35
    alpha: 255

spawner_grave:
  categoryConfiguredObjects:
  - Grave1
  name: Spawner Grave
  iconName: spawner
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 0
    green: 120
    blue: 0
    alpha: 255



#region Mistlands
# +-----------+
# | Mistlands |
# +-----------+

dungeon_infested_mines:
  categoryConfiguredObjects:
  - Mistlands_DvergrTownEntrance1
  - Mistlands_DvergrTownEntrance2
  name: Infested Mines
  iconName: dungeon
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 90
    green: 90
    blue: 90
    alpha: 255

dungeon_dvergr_camps_towers:
  categoryConfiguredObjects:
    - Mistlands_GuardTower1_new
    - Mistlands_GuardTower1_ruined_new
    - Mistlands_GuardTower1_ruined_new2
    - Mistlands_GuardTower2_new
    - Mistlands_GuardTower3_new
    - Mistlands_GuardTower3_ruined_new
  name: Guard Tower
  iconName: monument
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 90
    green: 90
    blue: 90
    alpha: 255

dungeon_dvergr_camps_excavation:
  categoryConfiguredObjects:
    - Mistlands_Excavation1
    - Mistlands_Excavation2
    - Mistlands_Excavation3
  name: Excavation
  iconName: mine
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 90
    green: 90
    blue: 90
    alpha: 255



#region Ashlands
# +----------+
# | Ashlands |
# +----------+

spawner_charred_stone:
  categoryConfiguredObjects:
  - CharredStone_Spawner
  name: Skeletons
  iconName: spawner
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 150
    green: 0
    blue: 0
    alpha: 255

dungeon_volture_nest:
  categoryConfiguredObjects:
  - VoltureNest
  name: Volture Nest
  iconName: bones
  isPermanent: true
  # Enable or Disable
  isActive: false
  iconColorRGBA:
    red: 255
    green: 135
    blue: 0
    alpha: 255


